
import { Translations, ThemeColor, Language, CategoryType } from './types';
import { 
  Home, 
  Heart, 
  User, 
  Plus, 
  Calendar, 
  Tag, 
  Image as ImageIcon,
  Sparkles,
  Download,
  Upload,
  Globe,
  Palette,
  Trash2,
  Edit3,
  Activity,
  Smartphone,
  Shirt,
  Armchair,
  BookOpen,
  Dumbbell,
  Box,
  PieChart,
  Moon,
  Sun,
  Monitor,
  HeartPulse,
  Database,
  X,
  BarChart2,
  Clock,
  Layers,
  TrendingUp,
  Share2,
  Copy,
  ChevronRight,
  ChevronDown,
  Search,
  SlidersHorizontal
} from 'lucide-react';

export const ICONS = {
  Home, Heart, User, Plus, Calendar, Tag, ImageIcon, Sparkles, Download, Upload, Globe, Palette, Trash2, Edit3, Activity,
  Smartphone, Shirt, Armchair, BookOpen, Dumbbell, Box, PieChart, Moon, Sun, Monitor, HeartPulse, Database, X,
  BarChart2, Clock, Layers, TrendingUp, Share2, Copy, ChevronRight, ChevronDown, Search, SlidersHorizontal
};

// Config for known categories. Custom ones will fallback to 'other' visuals but keep their name.
export const CATEGORY_CONFIG: Record<string, { icon: any, labelKey: string, color: string, bg: string }> = {
  digital: { icon: Smartphone, labelKey: 'catDigital', color: 'text-blue-500 dark:text-blue-400', bg: 'bg-blue-100 dark:bg-blue-900/30' },
  fashion: { icon: Shirt, labelKey: 'catFashion', color: 'text-rose-500 dark:text-rose-400', bg: 'bg-rose-100 dark:bg-rose-900/30' },
  home: { icon: Armchair, labelKey: 'catHome', color: 'text-orange-500 dark:text-orange-400', bg: 'bg-orange-100 dark:bg-orange-900/30' },
  beauty: { icon: Sparkles, labelKey: 'catBeauty', color: 'text-pink-500 dark:text-pink-400', bg: 'bg-pink-100 dark:bg-pink-900/30' },
  books: { icon: BookOpen, labelKey: 'catBooks', color: 'text-amber-500 dark:text-amber-400', bg: 'bg-amber-100 dark:bg-amber-900/30' },
  sports: { icon: Dumbbell, labelKey: 'catSports', color: 'text-emerald-500 dark:text-emerald-400', bg: 'bg-emerald-100 dark:bg-emerald-900/30' },
  health: { icon: HeartPulse, labelKey: 'catHealth', color: 'text-red-500 dark:text-red-400', bg: 'bg-red-100 dark:bg-red-900/30' },
  other: { icon: Box, labelKey: 'catOther', color: 'text-gray-500 dark:text-gray-400', bg: 'bg-gray-100 dark:bg-gray-800' },
};

export const DEFAULT_CHANNELS = ['JD', 'Taobao', 'PDD', 'Xianyu', 'Douyin'];
export const DEFAULT_STATUSES = ['new', 'used', 'broken', 'sold', 'emptied'];

export const THEMES: Record<ThemeColor, { primary: string; secondary: string; surface: string; onSurface: string; container: string }> = {
  blue: { 
    primary: 'bg-blue-600 dark:bg-blue-500', 
    secondary: 'text-blue-600 dark:text-blue-400', 
    surface: 'bg-blue-50 dark:bg-slate-950', 
    onSurface: 'text-blue-900 dark:text-blue-100', 
    container: 'bg-blue-100 dark:bg-blue-900/20' 
  },
  green: { 
    primary: 'bg-emerald-600 dark:bg-emerald-500', 
    secondary: 'text-emerald-600 dark:text-emerald-400', 
    surface: 'bg-emerald-50 dark:bg-slate-950', 
    onSurface: 'text-emerald-900 dark:text-emerald-100', 
    container: 'bg-emerald-100 dark:bg-emerald-900/20' 
  },
  violet: { 
    primary: 'bg-violet-600 dark:bg-violet-500', 
    secondary: 'text-violet-600 dark:text-violet-400', 
    surface: 'bg-violet-50 dark:bg-slate-950', 
    onSurface: 'text-violet-900 dark:text-violet-100', 
    container: 'bg-violet-100 dark:bg-violet-900/20' 
  },
  orange: { 
    primary: 'bg-orange-600 dark:bg-orange-500', 
    secondary: 'text-orange-600 dark:text-orange-400', 
    surface: 'bg-orange-50 dark:bg-slate-950', 
    onSurface: 'text-orange-900 dark:text-orange-100', 
    container: 'bg-orange-100 dark:bg-orange-900/20' 
  },
  rose: { 
    primary: 'bg-rose-600 dark:bg-rose-500', 
    secondary: 'text-rose-600 dark:text-rose-400', 
    surface: 'bg-rose-50 dark:bg-slate-950', 
    onSurface: 'text-rose-900 dark:text-rose-100', 
    container: 'bg-rose-100 dark:bg-rose-900/20' 
  },
};

export const TEXTS: Translations = {
  tabOwned: { 'zh-CN': '已购', 'zh-TW': '已購', 'en': 'Owned', 'ja': '購入済み' },
  tabWishlist: { 'zh-CN': '心愿单', 'zh-TW': '心願單', 'en': 'Wishlist', 'ja': 'ほしい物' },
  tabStats: { 'zh-CN': '统计', 'zh-TW': '統計', 'en': 'Stats', 'ja': '統計' },
  tabMine: { 'zh-CN': '我的', 'zh-TW': '我的', 'en': 'Mine', 'ja': 'マイ' },
  addItem: { 'zh-CN': '添加物品', 'zh-TW': '添加物品', 'en': 'Add Item', 'ja': 'アイテム追加' },
  editItem: { 'zh-CN': '编辑物品', 'zh-TW': '編輯物品', 'en': 'Edit Item', 'ja': 'アイテム編集' },
  quickAdd: { 'zh-CN': 'AI 快速添加', 'zh-TW': 'AI 快速添加', 'en': 'AI Quick Add', 'ja': 'AI クイック追加' },
  manualAdd: { 'zh-CN': '手动添加', 'zh-TW': '手動添加', 'en': 'Manual Add', 'ja': '手動追加' },
  showAiButton: { 'zh-CN': '显示 AI 按钮', 'zh-TW': '顯示 AI 按鈕', 'en': 'Show AI Button', 'ja': 'AIボタンを表示' },
  analyzeDesc: { 'zh-CN': '输入描述或上传图片，AI 将自动填写信息', 'zh-TW': '輸入描述或上傳圖片，AI 將自動填寫信息', 'en': 'Enter text or upload image, AI will fill details', 'ja': '説明を入力/画像をアップロードするとAIが自動入力します' },
  placeholderDesc: { 'zh-CN': '例如：昨天在京东买了索尼耳机，花了1200元...', 'zh-TW': '例如：昨天在京東買了索尼耳機，花了1200元...', 'en': 'E.g., Bought Sony headphones on Amazon yesterday for $200...', 'ja': '例：昨日Amazonでソニーのヘッドホンを買って、200ドル払った…' },
  analyzing: { 'zh-CN': '分析中...', 'zh-TW': '分析中...', 'en': 'Analyzing...', 'ja': '解析中...' },
  save: { 'zh-CN': '保存', 'zh-TW': '保存', 'en': 'Save', 'ja': '保存' },
  delete: { 'zh-CN': '删除', 'zh-TW': '刪除', 'en': 'Delete', 'ja': '削除' },
  confirm: { 'zh-CN': '确认', 'zh-TW': '確認', 'en': 'Confirm', 'ja': '確認' },
  ok: { 'zh-CN': '好的', 'zh-TW': '好的', 'en': 'OK', 'ja': 'OK' },
  notice: { 'zh-CN': '提示', 'zh-TW': '提示', 'en': 'Notice', 'ja': '通知' },
  none: { 'zh-CN': '暂无', 'zh-TW': '暫無', 'en': 'None', 'ja': 'なし' },
  cancel: { 'zh-CN': '取消', 'zh-TW': '取消', 'en': 'Cancel', 'ja': 'キャンセル' },
  name: { 'zh-CN': '名称', 'zh-TW': '名稱', 'en': 'Name', 'ja': '名称' },
  price: { 'zh-CN': '价格', 'zh-TW': '價格', 'en': 'Price', 'ja': '価格' },
  msrp: { 'zh-CN': '原价', 'zh-TW': '原價', 'en': 'MSRP', 'ja': '定価' },
  date: { 'zh-CN': '日期', 'zh-TW': '日期', 'en': 'Date', 'ja': '日付' },
  status: { 'zh-CN': '状态', 'zh-TW': '狀態', 'en': 'Status', 'ja': '状態' },
  category: { 'zh-CN': '分类', 'zh-TW': '分類', 'en': 'Category', 'ja': 'カテゴリ' },
  channel: { 'zh-CN': '购买渠道', 'zh-TW': '購買渠道', 'en': 'Channel', 'ja': '購入先' },
  note: { 'zh-CN': '备注', 'zh-TW': '備註', 'en': 'Note', 'ja': 'メモ' },
  link: { 'zh-CN': '链接', 'zh-TW': '鏈接', 'en': 'Link', 'ja': 'リンク' },
  import: { 'zh-CN': '导入数据', 'zh-TW': '導入數據', 'en': 'Import CSV', 'ja': 'データをインポート' },
  importFailed: { 'zh-CN': '??????????', 'zh-TW': '??????????', 'en': 'Import failed. Please check the file.', 'ja': '???????????????????????????' },
  export: { 'zh-CN': '导出数据', 'zh-TW': '導出數據', 'en': 'Export CSV', 'ja': 'データをエクスポート' },
  theme: { 'zh-CN': '主题颜色', 'zh-TW': '主題顏色', 'en': 'Theme Color', 'ja': 'テーマカラー' },
  language: { 'zh-CN': '语言', 'zh-TW': '語言', 'en': 'Language', 'ja': '言語' },
  totalValue: { 'zh-CN': '总价值', 'zh-TW': '總價值', 'en': 'Total Value', 'ja': '総価値' },
  itemCount: { 'zh-CN': '物品数量', 'zh-TW': '物品數量', 'en': 'Item Count', 'ja': 'アイテム数' },
  valPerDay: { 'zh-CN': '日均价值', 'zh-TW': '日均價值', 'en': 'Cost/Day', 'ja': '1日あたり' },
  valPerUse: { 'zh-CN': '次均价值', 'zh-TW': '次均價值', 'en': 'Cost/Use', 'ja': '1回あたり' },
  itemType: { 'zh-CN': '所属列表', 'zh-TW': '所屬列表', 'en': 'List', 'ja': '所属リスト' },
  valueDisplay: { 'zh-CN': '价值显示', 'zh-TW': '價值顯示', 'en': 'Value Display', 'ja': '価値表示' },
  valueDisplayBoth: { 'zh-CN': '同时显示', 'zh-TW': '同時顯示', 'en': 'Show Both', 'ja': '両方表示' },
  usage: { 'zh-CN': '使用次数', 'zh-TW': '使用次數', 'en': 'Usage', 'ja': '使用回数' },
  addUsage: { 'zh-CN': '+1次', 'zh-TW': '+1次', 'en': '+1 Use', 'ja': '+1回' },
  deleteConfirm: { 'zh-CN': '确定删除吗？', 'zh-TW': '確定刪除嗎？', 'en': 'Delete item?', 'ja': '削除しますか？' },
  deleteCategoryConfirm: { 'zh-CN': '删除该分类会将相关物品归为“其他”，继续吗？', 'zh-TW': '刪除該分類會將相關物品歸爲“其他”，繼續嗎？', 'en': 'Deleting this category will move related items to "other". Continue?', 'ja': 'このカテゴリを削除すると関連アイテムは「その他」に移動します。続けますか？' },
  deleteStatusConfirm: { 'zh-CN': '删除该状态会将相关物品状态设为“全新”，继续吗？', 'zh-TW': '刪除該狀態會將相關物品狀態設爲“全新”，繼續嗎？', 'en': 'Deleting this status will reset related items to "new". Continue?', 'ja': 'この状態を削除すると関連アイテムは「新品」に戻ります。続けますか？' },
  deleteChannelConfirm: { 'zh-CN': '删除该来源会清空相关物品的来源，继续吗？', 'zh-TW': '刪除該來源會清空相關物品的來源，繼續嗎？', 'en': 'Deleting this channel will clear related items. Continue?', 'ja': 'この購入先を削除すると関連アイテムの購入先がクリアされます。続けますか？' },
  filterAll: { 'zh-CN': '全部', 'zh-TW': '全部', 'en': 'All', 'ja': 'すべて' },
  statsDuration: { 'zh-CN': '持有时长分布', 'zh-TW': '持有時長分佈', 'en': 'Duration Dist.', 'ja': '所有期間分布' },
  statsStatusDist: { 'zh-CN': '资产状态分布', 'zh-TW': '資產狀態分佈', 'en': 'Status Dist.', 'ja': '状態分布' },
  statsValDist: { 'zh-CN': '分类价值分布', 'zh-TW': '分類價值分佈', 'en': 'Value Dist.', 'ja': '価値分布' },
  statsCountDist: { 'zh-CN': '分类数量分布', 'zh-TW': '分類數量分佈', 'en': 'Count Dist.', 'ja': '数量分布' },
  statsTimeline: { 'zh-CN': '状态时间线', 'zh-TW': '狀態時間線', 'en': 'Status Timeline', 'ja': '状態タイムライン' },
  statusNew: { 'zh-CN': '全新', 'zh-TW': '全新', 'en': 'New', 'ja': '新品' },
  statusUsed: { 'zh-CN': '二手', 'zh-TW': '二手', 'en': 'Used', 'ja': '中古' },
  statusBroken: { 'zh-CN': '损坏', 'zh-TW': '損壞', 'en': 'Broken', 'ja': '故障' },
  statusSold: { 'zh-CN': '已售', 'zh-TW': '已售', 'en': 'Sold', 'ja': '売却済み' },
  statusEmptied: { 'zh-CN': '用罄', 'zh-TW': '用罄', 'en': 'Emptied', 'ja': '使い切り' },
  chanJD: { 'zh-CN': '京东', 'zh-TW': '京東', 'en': 'JD', 'ja': 'JD' },
  chanTaobao: { 'zh-CN': '淘宝', 'zh-TW': '淘寶', 'en': 'Taobao', 'ja': '淘宝' },
  chanPDD: { 'zh-CN': '拼多多', 'zh-TW': '拼多多', 'en': 'Pinduoduo', 'ja': '拼多多' },
  chanXianyu: { 'zh-CN': '闲鱼', 'zh-TW': '閒魚', 'en': 'Xianyu', 'ja': 'Xianyu' },
  chanDouyin: { 'zh-CN': '抖音', 'zh-TW': '抖音', 'en': 'Douyin', 'ja': '抖音' },
  statsOverview: { 'zh-CN': '资产概览', 'zh-TW': '資產概覽', 'en': 'Overview', 'ja': '概要' },
  statsCategory: { 'zh-CN': '分类支出趋势', 'zh-TW': '分類支出趨勢', 'en': 'By Category', 'ja': 'カテゴリ別' },
  catDigital: { 'zh-CN': '数码', 'zh-TW': '數碼', 'en': 'Digital', 'ja': 'デジタル' },
  catFashion: { 'zh-CN': '服饰', 'zh-TW': '服飾', 'en': 'Fashion', 'ja': 'ファッション' },
  catHome: { 'zh-CN': '家居', 'zh-TW': '家居', 'en': 'Home', 'ja': 'ホーム' },
  catBeauty: { 'zh-CN': '美妆', 'zh-TW': '美妝', 'en': 'Beauty', 'ja': 'ビューティー' },
  catBooks: { 'zh-CN': '书籍', 'zh-TW': '書籍', 'en': 'Books', 'ja': '書籍' },
  catSports: { 'zh-CN': '运动', 'zh-TW': '運動', 'en': 'Sports', 'ja': 'スポーツ' },
  catHealth: { 'zh-CN': '健康', 'zh-TW': '健康', 'en': 'Health', 'ja': 'ヘルス' },
  catOther: { 'zh-CN': '其他', 'zh-TW': '其他', 'en': 'Other', 'ja': 'その他' },
  appearance: { 'zh-CN': '外观模式', 'zh-TW': '外觀模式', 'en': 'Appearance', 'ja': '外観モード' },
  modeLight: { 'zh-CN': '浅色', 'zh-TW': '淺色', 'en': 'Light', 'ja': 'ライト' },
  modeDark: { 'zh-CN': '深色', 'zh-TW': '深色', 'en': 'Dark', 'ja': 'ダーク' },
  modeSystem: { 'zh-CN': '跟随系统', 'zh-TW': '跟隨系統', 'en': 'System', 'ja': 'システム' },
  custom: { 'zh-CN': '自定义', 'zh-TW': '自定義', 'en': 'Custom', 'ja': 'カスタム' },
  manageData: { 'zh-CN': '数据管理', 'zh-TW': '數據管理', 'en': 'Manage Data', 'ja': 'データ管理' },
  manageCat: { 'zh-CN': '分类管理', 'zh-TW': '分類管理', 'en': 'Manage Categories', 'ja': 'カテゴリ管理' },
  manageStatus: { 'zh-CN': '状态管理', 'zh-TW': '狀態管理', 'en': 'Manage Statuses', 'ja': '状態管理' },
  manageChan: { 'zh-CN': '来源管理', 'zh-TW': '來源管理', 'en': 'Manage Channels', 'ja': '購入先管理' },
  addCategory: { 'zh-CN': '添加分类', 'zh-TW': '添加分類', 'en': 'Add Category', 'ja': 'カテゴリ追加' },
  addStatus: { 'zh-CN': '添加状态', 'zh-TW': '添加狀態', 'en': 'Add Status', 'ja': '状態追加' },
  addChannel: { 'zh-CN': '添加来源', 'zh-TW': '添加來源', 'en': 'Add Channel', 'ja': '購入先追加' },
  editLabel: { 'zh-CN': '编辑名称', 'zh-TW': '編輯名稱', 'en': 'Edit', 'ja': '編集' },
  inputName: { 'zh-CN': '输入名称', 'zh-TW': '輸入名稱', 'en': 'Enter a name', 'ja': '名称を入力' },
  aiSettings: { 'zh-CN': 'AI 设置', 'zh-TW': 'AI 設置', 'en': 'AI Settings', 'ja': 'AI設定' },
  aiProvider: { 'zh-CN': '服务商', 'zh-TW': '服務商', 'en': 'Provider', 'ja': 'プロバイダー' },
  aiApiKey: { 'zh-CN': 'API KEY', 'zh-TW': 'API KEY', 'en': 'API Key', 'ja': 'APIキー' },
  aiModel: { 'zh-CN': '模型', 'zh-TW': '模型', 'en': 'Model', 'ja': 'モデル' },
  aiBaseUrl: { 'zh-CN': 'Base URL', 'zh-TW': 'Base URL', 'en': 'Base URL', 'ja': 'ベースURL' },
  aiDisabled: { 'zh-CN': '禁用 AI', 'zh-TW': '禁用 AI', 'en': 'Disable AI', 'ja': 'AIを無効' },
  aiOpenAI: { 'zh-CN': 'OpenAI', 'zh-TW': 'OpenAI', 'en': 'OpenAI', 'ja': 'OpenAI' },
  aiGemini: { 'zh-CN': 'Google Gemini', 'zh-TW': 'Google Gemini', 'en': 'Google Gemini', 'ja': 'Google Gemini' },
  aiAnthropic: { 'zh-CN': 'Anthropic', 'zh-TW': 'Anthropic', 'en': 'Anthropic', 'ja': 'Anthropic' },
  aiDeepSeek: { 'zh-CN': 'DeepSeek', 'zh-TW': 'DeepSeek', 'en': 'DeepSeek', 'ja': 'DeepSeek' },
  aiMoonshot: { 'zh-CN': 'Moonshot', 'zh-TW': 'Moonshot', 'en': 'Moonshot', 'ja': 'Moonshot' },
  aiQwen: { 'zh-CN': 'Qwen', 'zh-TW': 'Qwen', 'en': 'Qwen', 'ja': 'Qwen' },
  aiZhipu: { 'zh-CN': 'Z.ai', 'zh-TW': 'Z.ai', 'en': 'Z.ai', 'ja': 'Z.ai' },
  aiMissingKey: { 'zh-CN': '请先在“我的 > AI 设置”中配置 API Key', 'zh-TW': '請先在“我的 > AI 設置”中配置 API Key', 'en': 'Please set your API Key in Profile > AI Settings first.', 'ja': '「マイ > AI設定」でAPIキーを設定してください' },
  aiMissingProvider: { 'zh-CN': '请先选择 AI 服务商', 'zh-TW': '請先選擇 AI 服務商', 'en': 'Please choose an AI provider first.', 'ja': '先にAIプロバイダーを選択してください' },
  alreadyExists: { 'zh-CN': '已存在', 'zh-TW': '已存在', 'en': 'Name already exists.', 'ja': '既に存在します' },
  requiredTag: { 'zh-CN': '不能为空', 'zh-TW': '不能爲空', 'en': 'This item is required and cannot be deleted.', 'ja': 'この項目は必須のため削除できません' },
  confirmDeleteTag: { 'zh-CN': '确定删除该项吗？', 'zh-TW': '確定刪除該項嗎？', 'en': 'Delete this tag?', 'ja': 'この項目を削除しますか？' },
  newCategoryPrompt: { 'zh-CN': '请输入新分类', 'zh-TW': '請輸入新分類', 'en': 'New Category Name', 'ja': '新しいカテゴリ名' },
  newChannelPrompt: { 'zh-CN': '请输入新来源', 'zh-TW': '請輸入新來源', 'en': 'New Channel Name', 'ja': '新しい購入先名' },
  exportTitle: { 'zh-CN': '导出数据', 'zh-TW': '導出數據', 'en': 'Export Data', 'ja': 'データをエクスポート' },
  exportDesc: { 'zh-CN': '选择导出方式', 'zh-TW': '選擇導出方式', 'en': 'Select export method. If save fails, try copying.', 'ja': 'エクスポート方法を選択してください。保存できない場合はコピーしてください。' },
  btnSaveFile: { 'zh-CN': '保存为文件', 'zh-TW': '保存爲文件', 'en': 'Save to File', 'ja': 'ファイルとして保存' },
  btnShareFile: { 'zh-CN': '分享文件', 'zh-TW': '分享文件', 'en': 'Share File', 'ja': 'ファイルを共有' },
  btnCopy: { 'zh-CN': '复制内容', 'zh-TW': '複製內容', 'en': 'Copy Content', 'ja': '内容をコピー' },
  copySuccess: { 'zh-CN': '复制成功', 'zh-TW': '複製成功', 'en': 'Copied!', 'ja': 'コピーしました' },
  exportSuccess: { 'zh-CN': '导出成功', 'zh-TW': '導出成功', 'en': 'Export successful!', 'ja': 'エクスポート成功' },
  manualCopyTip: { 'zh-CN': '已复制到剪贴板，可手动保存', 'zh-TW': '已複製到剪貼板，可手動保存', 'en': 'If buttons fail, manually copy the text below:', 'ja': 'ボタンが使えない場合、下のテキストを手動でコピーしてください' },
  saveFailed: { 'zh-CN': '保存失败', 'zh-TW': '保存失敗', 'en': 'Save failed. Please copy the text below.', 'ja': '保存に失敗しました。下のテキストをコピーしてください。' },
  shareNotSupported: { 'zh-CN': '当前设备不支持分享。', 'zh-TW': '當前設備不支持分享。', 'en': 'Sharing is not supported on this device.', 'ja': 'このデバイスでは共有できません。' },
  copyFailed: { 'zh-CN': '复制失败', 'zh-TW': '複製失敗', 'en': 'Copy failed.', 'ja': 'コピーに失敗しました。' },
  searchPlaceholder: { 'zh-CN': '搜索名称/备注/渠道...', 'zh-TW': '搜索名稱/備註/渠道...', 'en': 'Search name/note/channel?', 'ja': '名称/メモ/購入先を検索...' },
  advancedFilter: { 'zh-CN': '高级筛选', 'zh-TW': '高級篩選', 'en': 'Advanced Filters', 'ja': '高度なフィルター' },
  clearFilter: { 'zh-CN': '清空筛选', 'zh-TW': '清空篩選', 'en': 'Clear Filters', 'ja': 'フィルターをクリア' },
  dateStart: { 'zh-CN': '开始日期', 'zh-TW': '開始日期', 'en': 'Start Date', 'ja': '開始日' },
  dateEnd: { 'zh-CN': '结束日期', 'zh-TW': '結束日期', 'en': 'End Date', 'ja': '終了日' },
  priceMin: { 'zh-CN': '最低价格', 'zh-TW': '最低價格', 'en': 'Min Price', 'ja': '最低価格' },
  priceMax: { 'zh-CN': '最高价格', 'zh-TW': '最高價格', 'en': 'Max Price', 'ja': '最高価格' },
  statsMonthlyTrend: { 'zh-CN': '按月支出趋势', 'zh-TW': '按月支出趨勢', 'en': 'Monthly Spend Trend', 'ja': '月別支出トレンド' },
  statsCategoryTrend: { 'zh-CN': '分类支出趋势', 'zh-TW': '分類支出趨勢', 'en': 'Category Spend Trend', 'ja': 'カテゴリ支出トレンド' },
  statsChannelTrend: { 'zh-CN': '渠道支出趋势', 'zh-TW': '渠道支出趨勢', 'en': 'Channel Spend Trend', 'ja': '購入先支出トレンド' },
  channelUnknown: { 'zh-CN': '未知渠道', 'zh-TW': '未知渠道', 'en': 'Unlabeled', 'ja': '未分類' },
  priceHistory: { 'zh-CN': '历史价格走势', 'zh-TW': '歷史價格走勢', 'en': 'Price History', 'ja': '価格履歴' },
  priceHistoryTip: { 'zh-CN': '可按时间记录', 'zh-TW': '可按時間記錄', 'en': 'Record snapshots over time', 'ja': '時間ごとに記録' },
  priceHistoryDate: { 'zh-CN': '记录日期', 'zh-TW': '記錄日期', 'en': 'Date', 'ja': '記録日' },
  priceHistoryPrice: { 'zh-CN': '记录价格', 'zh-TW': '記錄價格', 'en': 'Price', 'ja': '記録価格' },
  priceHistoryAdd: { 'zh-CN': '添加价格记录', 'zh-TW': '添加價格記錄', 'en': 'Add Price Point', 'ja': '価格記録を追加' },
  priceHistoryEmpty: { 'zh-CN': '暂无记录', 'zh-TW': '暫無記錄', 'en': 'No price history', 'ja': '記録なし' },
  priceHistoryInvalid: { 'zh-CN': '请输入有效日期和价格', 'zh-TW': '請輸入有效日期和價格', 'en': 'Enter a valid date and price', 'ja': '有効な日付と価格を入力してください' },
  priceHistoryShort: { 'zh-CN': '价格记录', 'zh-TW': '價格記錄', 'en': 'History', 'ja': '履歴' },
  priceHistoryLatest: { 'zh-CN': '最新', 'zh-TW': '最新', 'en': 'Latest', 'ja': '最新' },
  priceHistoryMin: { 'zh-CN': '最低', 'zh-TW': '最低', 'en': 'Min', 'ja': '最低' },
  priceHistoryMax: { 'zh-CN': '最高', 'zh-TW': '最高', 'en': 'Max', 'ja': '最高' },
  noItemsYet: { 'zh-CN': '暂无物品', 'zh-TW': '暫無物品', 'en': 'No items yet', 'ja': 'まだアイテムがありません' },
  noData: { 'zh-CN': '暂无数据', 'zh-TW': '暫無數據', 'en': 'No data', 'ja': 'データなし' },
  noActivity: { 'zh-CN': '暂无动态', 'zh-TW': '暫無動態', 'en': 'No activity', 'ja': 'アクティビティなし' },
  addImage: { 'zh-CN': '添加图片', 'zh-TW': '添加圖片', 'en': 'Add Image', 'ja': '画像を追加' },
  itemNamePlaceholder: { 'zh-CN': '物品名称', 'zh-TW': '物品名稱', 'en': 'Item Name', 'ja': 'アイテム名' },
  unknownItem: { 'zh-CN': '未知物品', 'zh-TW': '未知物品', 'en': 'Unknown Item', 'ja': '不明なアイテム' },
  imagePreviewAlt: { 'zh-CN': '预览', 'zh-TW': '預覽', 'en': 'Preview', 'ja': 'プレビュー' },
  linkPlaceholder: { 'zh-CN': 'https://...', 'zh-TW': 'https://...', 'en': 'https://...', 'ja': 'https://...' },
  aiAnalyzeFailed: { 'zh-CN': 'AI 分析失败，请重试', 'zh-TW': 'AI 分析失敗，請重試', 'en': 'AI analysis failed. Please try manual entry.', 'ja': 'AI解析に失敗しました。手動入力を試してください。' },
};

export const INITIAL_ITEMS = [];

